package org.antlr.jetbrains.wichplugin.genwindow;

import com.intellij.ui.components.JBPanel;
import com.intellij.ui.components.JBScrollPane;
import com.intellij.ui.components.JBTabbedPane;

import javax.swing.*;
import java.awt.*;

public class WichToolWindow extends JBPanel {
	private JBTabbedPane tabs;
	private JBScrollPane CTab;
	private JTextArea Coutput;
	private JBScrollPane LLVMTab;
	private JTextArea LLVMoutput;
	private JBScrollPane BytecodeTab;
	private JTextArea Bytecodeoutput;
	private JTextArea execOutput;
	private JBScrollPane execScrollPane;

	public WichToolWindow() {
		super(new BorderLayout());
		setupGUI();
	}

	public void setupGUI() {
		CTab = new JBScrollPane();
		Coutput = new JTextArea();
		Coutput.setText("Generated C code");
		CTab.setViewportView(Coutput);

		LLVMTab = new JBScrollPane();
		LLVMoutput = new JTextArea();
		LLVMoutput.setText("Generated LLVM code");
		LLVMTab.setViewportView(LLVMoutput);

		BytecodeTab = new JBScrollPane();
		Bytecodeoutput = new JTextArea();
		Bytecodeoutput.setText("Generated Bytecode");
		BytecodeTab.setViewportView(Bytecodeoutput);

		tabs = new JBTabbedPane();
		tabs.addTab("C", CTab);
		tabs.addTab("LLVM", LLVMTab);
		tabs.addTab("Bytecode", BytecodeTab);

		execScrollPane = new JBScrollPane();
		execOutput = new JTextArea(3,80);
		execOutput.setText("foo");
		execScrollPane.setViewportView(execOutput);

		add(tabs, BorderLayout.CENTER);
		add(execScrollPane, BorderLayout.SOUTH);
	}
}
